-- SQL Schema for Pioneer Group Garments Tracker
-- Run this in your Supabase SQL Editor to set up the 'orders' table

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bundle_id TEXT UNIQUE NOT NULL,
  buyer TEXT DEFAULT 'TBA',
  style TEXT NOT NULL,
  po TEXT NOT NULL,
  color TEXT DEFAULT 'N/A',
  size TEXT DEFAULT 'N/A',
  po_quantity INTEGER DEFAULT 0,
  
  -- Process Quantities
  cutting_in INTEGER DEFAULT 0,
  cutting_out INTEGER DEFAULT 0,
  sew_in INTEGER DEFAULT 0,
  sew_out INTEGER DEFAULT 0,
  send_to_wash INTEGER DEFAULT 0,
  wash_in INTEGER DEFAULT 0,
  wash_out INTEGER DEFAULT 0,
  fin_in INTEGER DEFAULT 0,
  fin_out INTEGER DEFAULT 0,
  
  -- Line Tracking
  line TEXT DEFAULT 'N/A',
  sewing_line TEXT DEFAULT 'N/A',
  finishing_line TEXT DEFAULT 'N/A',
  cutting_line TEXT DEFAULT 'N/A',
  wash_line TEXT DEFAULT 'N/A',
  
  -- Rejection Summary (Integrated into orders table)
  total_rejections INTEGER DEFAULT 0,
  last_rejection_at TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Rejection Logs (To store every individual rejection event)
CREATE TABLE IF NOT EXISTS rejection_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bundle_id TEXT NOT NULL,
  buyer TEXT DEFAULT 'TBA',
  style TEXT NOT NULL,
  po TEXT NOT NULL,
  color TEXT DEFAULT 'N/A',
  size TEXT DEFAULT 'N/A',
  po_qty INTEGER DEFAULT 0,
  bundle_qty INTEGER DEFAULT 0,
  rejections_qty INTEGER DEFAULT 0,
  process TEXT NOT NULL,
  line TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for rejection_logs
ALTER TABLE rejection_logs ENABLE ROW LEVEL SECURITY;

-- Create policy for rejection_logs
CREATE POLICY "Allow all access to rejection_logs" 
ON rejection_logs FOR ALL 
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Indexes for rejection_logs
CREATE INDEX IF NOT EXISTS idx_rejection_logs_bundle_id ON rejection_logs(bundle_id);
CREATE INDEX IF NOT EXISTS idx_rejection_logs_created_at ON rejection_logs(created_at);

-- Function to handle updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for updated_at
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access (adjust for production as needed)
CREATE POLICY "Allow all access to authenticated users" 
ON orders FOR ALL 
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_bundle_id ON orders(bundle_id);
CREATE INDEX IF NOT EXISTS idx_orders_style ON orders(style);
CREATE INDEX IF NOT EXISTS idx_orders_po ON orders(po);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
