-- SQL Schema for Pioneer Group Garments Tracker
-- Run this in your Supabase SQL Editor to set up the 'orders' table

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  bundle_id TEXT NOT NULL,
  buyer TEXT DEFAULT 'TBA',
  style TEXT NOT NULL,
  po TEXT NOT NULL,
  color TEXT DEFAULT 'N/A',
  size TEXT DEFAULT 'N/A',
  po_quantity INTEGER DEFAULT 0,
  
  -- Process Quantities
  cutting_in INTEGER DEFAULT 0,
  cutting_out INTEGER DEFAULT 0,
  sew_in INTEGER DEFAULT 0,
  sew_out INTEGER DEFAULT 0,
  send_to_wash INTEGER DEFAULT 0,
  wash_in INTEGER DEFAULT 0,
  wash_out INTEGER DEFAULT 0,
  fin_in INTEGER DEFAULT 0,
  fin_out INTEGER DEFAULT 0,
  
  -- Line Tracking
  line TEXT DEFAULT 'N/A',
  sewing_line TEXT DEFAULT 'N/A',
  finishing_line TEXT DEFAULT 'N/A',
  cutting_line TEXT DEFAULT 'N/A',
  wash_line TEXT DEFAULT 'N/A',
  
  -- Rejection Summary (Integrated into orders table)
  total_rejections INTEGER DEFAULT 0,
  last_rejection_at TIMESTAMPTZ,
  
  -- Factory name to facilitate grouping/searching
  factory_name TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique constraint per user for bundle_id
  UNIQUE(user_id, bundle_id)
);

-- Rejection Logs (To store every individual rejection event)
CREATE TABLE IF NOT EXISTS rejection_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  bundle_id TEXT NOT NULL,
  buyer TEXT DEFAULT 'TBA',
  style TEXT NOT NULL,
  po TEXT NOT NULL,
  color TEXT DEFAULT 'N/A',
  size TEXT DEFAULT 'N/A',
  po_qty INTEGER DEFAULT 0,
  bundle_qty INTEGER DEFAULT 0,
  rejections_qty INTEGER DEFAULT 0,
  process TEXT NOT NULL,
  line TEXT NOT NULL,
  reason TEXT,
  factory_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Order Information table
CREATE TABLE IF NOT EXISTS order_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  buyer TEXT DEFAULT 'TBA',
  style TEXT NOT NULL,
  po TEXT NOT NULL,
  color TEXT DEFAULT 'N/A',
  size_data JSONB DEFAULT '[]'::jsonb,
  total_po_qty INTEGER DEFAULT 0,
  factory_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for all tables
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE rejection_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_info ENABLE ROW LEVEL SECURITY;

-- RLS Policies for orders
CREATE POLICY "All authenticated users can access all orders" 
ON orders FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- RLS Policies for rejection_logs
CREATE POLICY "All authenticated users can access all rejection logs" 
ON rejection_logs FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- RLS Policies for order_info
CREATE POLICY "All authenticated users can access all order info" 
ON order_info FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_bundle_id ON orders(bundle_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);

CREATE INDEX IF NOT EXISTS idx_rejection_logs_user_id ON rejection_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_rejection_logs_bundle_id ON rejection_logs(bundle_id);
CREATE INDEX IF NOT EXISTS idx_rejection_logs_created_at ON rejection_logs(created_at);

CREATE INDEX IF NOT EXISTS idx_order_info_user_id ON order_info(user_id);
CREATE INDEX IF NOT EXISTS idx_order_info_style ON order_info(style);
CREATE INDEX IF NOT EXISTS idx_order_info_po ON order_info(po);

-- Function to handle updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for updated_at for orders
CREATE TRIGGER set_updated_at_orders
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();

-- Trigger for updated_at for order_info
CREATE TRIGGER set_updated_at_order_info
BEFORE UPDATE ON order_info
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();
